import = ["~/.config/alacritty/themes/base2tone-forest.toml"]

[window]
startup_mode = "Maximized"  # Default: "Windowed"

[font]
size = 11
normal = { family = "CommitMono Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[cursor]
style = { shape = "Block", blinking = "On" }  # Default: shape = "Block", blinking = "Off"

[keyboard]
bindings = [
  # Super + Q to Quit
  { key = "Q", mods = "Control|Shift", action = "Quit" },
  # Super + N for New Window
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
