vim.pack.add({
  'https://github.com/ellisonleao/gruvbox.nvim',
  'https://github.com/ibhagwan/fzf-lua',
  'https://github.com/nvim-lua/plenary.nvim',
  'https://github.com/MunifTanjim/nui.nvim',
  'https://github.com/nvim-neo-tree/neo-tree.nvim',
  'https://github.com/karb94/neoscroll.nvim',
  'https://github.com/mfussenegger/nvim-dap',
  'https://github.com/stevearc/oil.nvim',
  'https://github.com/nvim-mini/mini.nvim',
  'https://github.com/esmuellert/codediff.nvim',
  'https://github.com/goolord/alpha-nvim',
  'https://github.com/nvim-lualine/lualine.nvim',
  'https://github.com/MeanderingProgrammer/render-markdown.nvim',
  'https://github.com/rafamadriz/friendly-snippets',
  { src = 'https://github.com/saghen/blink.cmp',           version = vim.version.range('1.x') },
  { src = 'https://github.com/nickjvandyke/opencode.nvim', version = 'v0.8.2' },
  'https://github.com/folke/snacks.nvim',
})
